### ISSUE TITLE
UnsatisfiedLinkError: Failed to load native TensorFlow Lite methods

### ISSUE THREAD

**Issue by gaikwadrahul8** [google-ai-edge/LiteRT#106]
### Describe the problem
Describe the problem clearly here. Be sure to convey here why it's a bug in TensorFlow or a feature request.

- TensorFlow Lite initialisation crashes when using versions 2.12 and above on any Android Emulator with API level between 21 and 25 included.

### Source code / logs
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached. Try to provide a reproducible test case that is the bare minimum necessary to generate the problem.

Steps to reproduce:
1. Create a new Android project.
2. Add TensorFlow Lite dependencies:
```
    implementation("org.tensorflow:tensorflow-lite:2.14.0")
    implementation("org.tensorflow:tensorflow-lite-support:0.4.3")
```
3. [Download](https://storage.googleapis.com/mediapipe-models/face_detector/blaze_face_short_range/float16/latest/blaze_face_short_range.tflite) BlazeFace tflite model and add to src/main/assets folder
4. Initialise Tensorflow Lite Interpreter in `onCreate()` of MainActivity:
```
        val model = FileUtil.loadMappedFile(this, "blaze_face_short_range.tflite")
        val options = Interpreter.Options()
        options.numThreads = 4
        val interpreter = Interpreter(model, options)
```
5. Run the app on any Android Emulator using API Level between 21 and 25 included.
6. App crashes with the following error:
```
 E  FATAL EXCEPTION: main
    Process: com.example.myapplication, PID: 8645
    java.lang.UnsatisfiedLinkError: Failed to load native TensorFlow Lite methods. Check that the correct native libraries are present, and, if using a custom native library, have been properly loaded via System.loadLibrary():
      java.lang.UnsatisfiedLinkError: dlopen failed: cannot locate symbol "strtod_l" referenced by "/data/app/com.example.myapplication-2/base.apk!/lib/arm64-v8a/libtensorflowlite_jni.so"...
    	at org.tensorflow.lite.TensorFlowLite.init(TensorFlowLite.java:137)
    	at org.tensorflow.lite.NativeInterpreterWrapper.<init>(NativeInterpreterWrapper.java:62)
    	at org.tensorflow.lite.NativeInterpreterWrapperExperimental.<init>(NativeInterpreterWrapperExperimental.java:36)
    	at org.tensorflow.lite.Interpreter.<init>(Interpreter.java:232)
    	at com.example.myapplication.MainActivity.onCreate(MainActivity.kt:35)
    	at android.app.Activity.performCreate(Activity.java:6679)
    	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1118)
    	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2618)
    	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2726)
    	at android.app.ActivityThread.-wrap12(ActivityThread.java)
    	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1477)
    	at android.os.Handler.dispatchMessage(Handler.java:102)
    	at android.os.Looper.loop(Looper.java:154)
    	at android.app.ActivityThread.main(ActivityThread.java:6119)
    	at java.lang.reflect.Method.invoke(Native Method)
    	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
    Caused by: java.lang.UnsatisfiedLinkError: No implementation found for void org.tensorflow.lite.TensorFlowLite.nativeDoNothing() (tried Java_org_tensorflow_lite_TensorFlowLite_nativeDoNothing and Java_org_tensorflow_lite_TensorFlowLite_nativeDoNothing__)
    	at org.tensorflow.lite.TensorFlowLite.nativeDoNothing(Native Method)
    	at org.tensorflow.lite.TensorFlowLite.init(TensorFlowLite.java:132)
    	at org.tensorflow.lite.NativeInterpreterWrapper.<init>(NativeInterpreterWrapper.java:62) 
    	at org.tensorflow.lite.NativeInterpreterWrapperExperimental.<init>(NativeInterpreterWrapperExperimental.java:36) 
    	at org.tensorflow.lite.Interpreter.<init>(Interpreter.java:232) 
    	at com.example.myapplication.MainActivity.onCreate(MainActivity.kt:35) 
    	at android.app.Activity.performCreate(Activity.java:6679) 
    	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1118) 
    	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2618) 
    	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2726) 
    	at android.app.ActivityThread.-wrap12(ActivityThread.java) 
    	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1477) 
    	at android.os.Handler.dispatchMessage(Handler.java:102) 
    	at android.os.Looper.loop(Looper.java:154) 
    	at android.app.ActivityThread.main(ActivityThread.java:6119) 
    	at java.lang.reflect.Method.invoke(Native Method) 
    	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886) 
    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776) 
```

**Comment by gaikwadrahul8** [comment]
This issue originally reported by @nijat-ahmadli has been moved to this dedicated repository for [LiteRT](https://github.com/google-ai-edge/LiteRT/) to enhance issue tracking and prioritization. To ensure continuity, we have created this new issue on your behalf.

We appreciate your understanding and look forward to your continued involvement.

**Comment by antonlookintwt** [comment]
I've been able to reproduce issue on Samsung Galaxy S6 with Android 7.0 and Android Emulator with Android 7.1. Both had same crashlog (attached below).

I am experiencing crash only when I have LiteRT dependencies:
`  
implementation("com.google.ai.edge.litert:litert:1.4.0")
implementation("com.google.ai.edge.litert:litert-gpu:1.4.0")
implementation("com.google.ai.edge.litert:litert-metadata:1.4.0")
implementation("com.google.ai.edge.litert:litert-support:1.4.0")
`

And no crash when rollback to latest tflite dependencies:
`  
implementation("org.tensorflow:tensorflow-lite:2.17.0")
implementation("org.tensorflow:tensorflow-lite-support:0.4.4")
implementation("org.tensorflow:tensorflow-lite-gpu-delegate-plugin:0.4.4")
implementation("org.tensorflow:tensorflow-lite-gpu-api:2.17.0")
implementation("org.tensorflow:tensorflow-lite-api:2.17.0")
implementation("org.tensorflow:tensorflow-lite-gpu:2.17.0")
` 

` Fatal Exception: java.lang.UnsatisfiedLinkError: Failed to load native TensorFlow Lite methods. Check that the correct native libraries are present, and, if using a custom native library, have been properly loaded via System.loadLibrary():
  java.lang.UnsatisfiedLinkError: dlopen failed: cannot locate symbol "strtod_l" referenced by "/data/app/de.ausbuettel.smartdraco.dev-2/lib/arm64/libtensorflowlite_jni.so"...
       at org.tensorflow.lite.TensorFlowLite.init(TensorFlowLite.java:137)
       at org.tensorflow.lite.NativeInterpreterWrapper.<init>(NativeInterpreterWrapper.java:62)
       at org.tensorflow.lite.NativeInterpreterWrapperExperimental.<init>(NativeInterpreterWrapperExperimental.java:36)
       at org.tensorflow.lite.Interpreter.<init>(Interpreter.java:230)
       at de.ausbuettel.smartdraco.detection.Yolo.initialize_model(Yolo.java:93)
       at de.ausbuettel.smartdraco.detection.Detector.setup(Detector.kt:25)
       at de.ausbuettel.smartdraco.SmarDracoApp$onCreate$1.invokeSuspend(SmarDracoApp.kt:82)
       at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
       at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:104)
       at kotlinx.coroutines.internal.LimitedDispatcher$Worker.run(LimitedDispatcher.java:111)
       at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:99)
       at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.java:584)
       at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:811)
       at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:715)
       at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:702)`

`Caused by java.lang.UnsatisfiedLinkError: No implementation found for void org.tensorflow.lite.TensorFlowLite.nativeDoNothing() (tried Java_org_tensorflow_lite_TensorFlowLite_nativeDoNothing and Java_org_tensorflow_lite_TensorFlowLite_nativeDoNothing__)
       at org.tensorflow.lite.TensorFlowLite.nativeDoNothing(TensorFlowLite.java)
       at org.tensorflow.lite.TensorFlowLite.init(TensorFlowLite.java:132)
       at org.tensorflow.lite.NativeInterpreterWrapper.<init>(NativeInterpreterWrapper.java:62)
       at org.tensorflow.lite.NativeInterpreterWrapperExperimental.<init>(NativeInterpreterWrapperExperimental.java:36)
       at org.tensorflow.lite.Interpreter.<init>(Interpreter.java:230)
       at de.ausbuettel.smartdraco.detection.Yolo.initialize_model(Yolo.java:93)
       at de.ausbuettel.smartdraco.detection.Detector.setup(Detector.kt:25)
       at de.ausbuettel.smartdraco.SmarDracoApp$onCreate$1.invokeSuspend(SmarDracoApp.kt:82)
       at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
       at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:104)
       at kotlinx.coroutines.internal.LimitedDispatcher$Worker.run(LimitedDispatcher.java:111)
       at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:99)
       at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.java:584)
       at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:811)
       at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:715)
       at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:702)`

Any chance you can take a look at this issue?

**Comment by pkgoogle** [comment]
Hi @antonlookintwt, Unfortunately we no longer support Those Android version for the latest LiteRT: https://ai.google.dev/edge/litert/android#supported_android_versions You can try older versions of the original TFLite runtime but they are not really being supported now either. I apologize that there isn't a better answer for you.

**Comment by fergushenderson** [comment]
This issue was tracking a regression in TF Lite 2.12 was fixed in TF Lite 2.16:
https://mvnrepository.com/artifact/org.tensorflow/tensorflow-lite/2.16.1

See  https://github.com/tensorflow/tensorflow/issues/62173#issuecomment-1791326432. 
and https://github.com/tensorflow/tensorflow/issues/61951#issuecomment-2066164967

Regrettably, this seems to have regressed again in LiteRT 1.4.0, and also in the LiteRT docs for LiteRT 1.2.0.
The new regression is being tracked in issue #3274.

> Hi @antonlookintwt, Unfortunately we no longer support Those Android version for the latest LiteRT: 
> https://ai.google.dev/edge/litert/android#supported_android_versions

This was never mentioned in the LiteRT release notes, and in my opinion has not had sufficient review,
and is not the right resolution.  This is a significant regression compared with TF Lite 2.17, and should be fixed.
The minimum supported API level should be 21, not 31.
