### ISSUE TITLE
I cannot run a transformer model with token-level output on accelerated hardware in TF Lite

### ISSUE THREAD

**Issue by pkgoogle** [google-ai-edge/LiteRT#134]
Original Issue: https://github.com/tensorflow/tensorflow/issues/59232
Opening on behalf of @DerEchteFeuerpfeil

# Description of the issue
Okay so to preface this, I have been working on this for over a month. My goal can be explained in one sentence: I want to run my small bert-like model with token-level output on the GPU of my Android phone using the Interpreter API and the GPU delegate. The Task API does unfortunately not offer that.

Please don't hesitate to reach out to me if you are missing any information to understand or reproduce this issue. I really want to get this working!

# System Information
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 10
- TensorFlow installed from (source or binary): binary
- TensorFlow version (or github SHA if from source): 2.10.1

# The model and the TF Lite conversion
I want to use a simple BERT-based model to classify something on token-level. The following code should get you an idea of the model:

```python
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers
from tokenizers import BertWordPieceTokenizer
from transformers import BertTokenizer, TFBertModel, BertConfig


 encoder_config = {
  "attention_probs_dropout_prob": 0.1,
  "model_type": "bert",
  "emb_size": 512,
  "hidden_act": "gelu",
  "hidden_dropout_prob": 0.1,
  "hidden_size": 1024,
  "initializer_range": 0.02,
  "intermediate_size": 3072,
  "max_position_embeddings": 128,
  "num_attention_heads": 8,
  "num_hidden_layers": 4,
  "type_vocab_size": 2,
  "vocab_size": 25000
}
configuration = BertConfig.from_dict(encoder_config)  # default parameters and configuration for BERT

def create_model(max_len = 128):
    ## BERT encoder
    encoder = TFBertModel(configuration)

    ## Classification Model
    input_ids = layers.Input(shape=(max_len,), dtype=tf.int64)
    token_type_ids = layers.Input(shape=(max_len,), dtype=tf.int64)
    attention_mask = layers.Input(shape=(max_len,), dtype=tf.int64)

    embedding = encoder(
        input_ids, token_type_ids=token_type_ids, attention_mask=attention_mask
    )[0]

    ## Token-level classification
    relu_layer = layers.Dense(80, activation="relu", name="relu_1")(embedding)
    classification_head = layers.Dense(len(config.get("labels")))(relu_layer)

    model = keras.Model(
        inputs=[input_ids, token_type_ids, attention_mask],
        outputs=[classification_head],
    )

    return model

model = create_model()
```
After I created the model, I converted it to the TF Lite format with the following code:
```python
converter = tf.lite.TFLiteConverter.from_keras_model(model)
converter.target_spec.supported_ops = [
  tf.lite.OpsSet.TFLITE_BUILTINS, # enable TensorFlow Lite ops.
  tf.lite.OpsSet.SELECT_TF_OPS
]
tflite_model = converter.convert()

# Save the model.
with open('../dev/model.tflite', 'wb') as f:
  f.write(tflite_model)
```

The conversion output the following text:
```
WARNING:absl:Found untraced functions such as embeddings_layer_call_fn, embeddings_layer_call_and_return_conditional_losses, encoder_layer_call_fn, encoder_layer_call_and_return_conditional_losses, pooler_layer_call_fn while saving (showing 5 of 216). These functions will not be directly callable after loading.
INFO:tensorflow:Assets written to: C:\Users\USERNAME\AppData\Local\Temp\tmpb4tsljq3\assets
INFO:tensorflow:Assets written to: C:\Users\USERNAME\AppData\Local\Temp\tmpb4tsljq3\assets
```
But this did not bother me too much as these don't seem to be errors.

# Running the model on Android with hardware acceleration
To not introduce any errors from my side, I decided to use the [pre-built benchmarking app](https://www.tensorflow.org/lite/performance/measurement#android_benchmark_app) that TensorFlow provides. All the following adb commands are taken from that page.

First, I installed the app and pushed my model to the phone, which is in my case, a Pixel 3a.
```
adb install -r -d -g android_aarch64_benchmark_model.apk
adb push model.tflite /data/local/tmp
```

## Running the model on CPU
Then, I ran the model on the CPU to see if everything works:
```
adb shell am start -S -n org.tensorflow.lite.benchmark/.BenchmarkModelActivity --es args '"--graph=/data/local/tmp/model.tflite --num_threads=1"'
```
and get the following output, where everything worked as expected:
```
01-11 23:28:57.758  7651  7651 I tflite_BenchmarkModelActivity: Running TensorFlow Lite benchmark with args: --graph=/data/local/tmp/model.tflite
01-11 23:28:59.026  7651  7651 I tflite  : Log parameter values verbosely: [0]
01-11 23:28:59.026  7651  7651 I tflite  : Graph: [/data/local/tmp/model.tflite]
01-11 23:28:59.028  7651  7651 I tflite  : Loaded model /data/local/tmp/model.tflite
01-11 23:28:59.028  7651  7651 I tflite  : Initialized TensorFlow Lite runtime.
01-11 23:28:59.034  7651  7651 I tflite  : Created TensorFlow Lite XNNPACK delegate for CPU.
01-11 23:28:59.036  7651  7651 I tflite  : The input model file size (MB): 137.514
01-11 23:28:59.036  7651  7651 I tflite  : Initialized session in 9.34ms.
01-11 23:28:59.036  7651  7651 I tflite  : Running benchmark for at least 1 iterations and at least 0.5 seconds but terminate if exceeding 150 seconds.
01-11 23:29:03.662  7651  7651 I tflite  : count=1 curr=1381510
01-11 23:29:03.662  7651  7651 I tflite  : Running benchmark for at least 50 iterations and at least 1 seconds but terminate if exceeding 150 seconds.
01-11 23:29:24.958  7651  7651 I tflite  : count=50 first=505840 curr=424069 min=421685 max=505840 avg=425911 std=11770
01-11 23:29:24.958  7651  7651 I tflite  : Inference timings in us: Init: 9340, First inference: 1381510, Warmup (avg): 1.38151e+06, Inference (avg): 425911
01-11 23:29:24.958  7651  7651 I tflite  : Note: as the benchmark tool itself affects memory footprint, the following is only APPROXIMATE to the actual memory footprint of the model at runtime. Take the information at your discretion.
01-11 23:29:24.958  7651  7651 I tflite  : Memory footprint delta from the start of the tool (MB): init=1.84766 overall=117.375
```

## Running the model on GPU
After the successful run on CPU, I want to make use of hardware acceleration to see whether this would speedup my inference and therefore I ran this command:
```
adb shell am start -S -n org.tensorflow.lite.benchmark/.BenchmarkModelActivity --es args '"--graph=/data/local/tmp/model.tflite --use_gpu=true"'
```
which output this:
```
01-11 23:31:59.519  8399  8399 I tflite_BenchmarkModelActivity: Running TensorFlow Lite benchmark with args: --graph=/data/local/tmp/model.tflite --use_gpu=true
01-11 23:31:59.706  8399  8399 I tflite  : Log parameter values verbosely: [0]
01-11 23:31:59.706  8399  8399 I tflite  : Graph: [/data/local/tmp/model.tflite]
01-11 23:31:59.707  8399  8399 I tflite  : Use gpu: [1]
01-11 23:31:59.708  8399  8399 I tflite  : Loaded model /data/local/tmp/model.tflite
01-11 23:31:59.709  8399  8399 I tflite  : Initialized TensorFlow Lite runtime.
01-11 23:31:59.713  8399  8399 I tflite  : Created TensorFlow Lite delegate for GPU.
01-11 23:31:59.713  8399  8399 I tflite  : GPU delegate created.
01-11 23:31:59.715  8399  8399 E tflite  : Failed to apply GPU delegate.
```

There is no more information extractable from the benchmarking app, which is why I wrote an app where I can print the stacktrace of the error. And **when I try to create an Interpreter Object with the Interpreter API with a GPU delegate as options**, I get the following error:
```
I/tflite: Created TensorFlow Lite delegate for GPU.
W/System.err: java.lang.IllegalArgumentException: Internal error: Error applying delegate:
W/System.err:     at org.tensorflow.lite.NativeInterpreterWrapper.createInterpreter(Native Method)
W/System.err:     at org.tensorflow.lite.NativeInterpreterWrapper.init(NativeInterpreterWrapper.java:106)
W/System.err:     at org.tensorflow.lite.NativeInterpreterWrapper.<init>(NativeInterpreterWrapper.java:58)
W/System.err:     at org.tensorflow.lite.NativeInterpreterWrapperExperimental.<init>(NativeInterpreterWrapperExperimental.java:32)
W/System.err:     at org.tensorflow.lite.Interpreter.<init>(Interpreter.java:197)
W/System.err:     at com.example.mobileinferencedemo.inference.PunctuationInference.<init>(PunctuationInference.kt:115)
W/System.err:     at com.example.mobileinferencedemo.MainActivity.onCreate(MainActivity.kt:28)
W/System.err:     at android.app.Activity.performCreate(Activity.java:8054)
W/System.err:     at android.app.Activity.performCreate(Activity.java:8034)
W/System.err:     at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1341)
W/System.err:     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3688)
W/System.err:     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3864)
W/System.err:     at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:103)
W/System.err:     at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
W/System.err:     at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
W/System.err:     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2253)
W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:106)
W/System.err:     at android.os.Looper.loopOnce(Looper.java:201)
W/System.err:     at android.os.Looper.loop(Looper.java:288)
W/System.err:     at android.app.ActivityThread.main(ActivityThread.java:7870)
W/System.err:     at java.lang.reflect.Method.invoke(Native Method)
W/System.err:     at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
W/System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
```

It is important to note where this application fails. It fails when I try to create an Interpreter Object with the Interpreter API with a GPU delegate as options. I did not run any inference, I just wanted to create the Interpreter. If you're curious, here is the code for that (which I took from [the docs](https://www.tensorflow.org/lite/android/delegates/gpu#use_gpu_with_interpreter_api)):
```kotlin
val compatList = CompatibilityList()

val options = Interpreter.Options().apply{
    if(compatList.isDelegateSupportedOnThisDevice){
        val delegateOptions = compatList.bestOptionsForThisDevice
        this.addDelegate(GpuDelegate(delegateOptions))
    } else {
        this.numThreads = 4
    }
}

try {
    val myInterpreter: Interpreter
    if(options != null){
        myInterpreter = Interpreter(File(path.toString()), options)
    } else {
        myInterpreter = Interpreter(File(path.toString()))
    }

    myInterpreter.close()
} catch (e: Exception) {
    Log.e("tf_load_model",""+e.message)
    e.printStackTrace()
}
```

This try block already fails when trying to create the Interpreter (which I manually confirmed in the Android Studio debugger).

# Steps to reproduce this issue
1. Create the model with the code provided at the start of this issue
2. Convert it to TF lite with the code above
3. Try to run the converted TF lite model on the phone using the pre-built TensorFlow lite benchmarking app and use the `--use_gpu=true` flag
4. Observe the error "Failed to apply GPU delegate"

# Additional information
I really am curious if this is an error from my side or just generally a bug. The steps for reproducing the error should be rather quick, so I hope someone can look into this. There are just almost no resources on this, which makes it really hard to know if someone else succeeded running a token-level transformer model on the GPU using the Interpreter API. If this matter resolves, I would be happy to contribute a resource or guide to this.

## The question of operator support
There is a [list of supported ML operations for GPU](https://www.tensorflow.org/lite/performance/gpu#supported_ops) inference with the GPU delegate.

When printing the operators of my converted TF lite model in python
```python
interpreter = tf.lite.Interpreter(model_path="..\dev\model.tflite")
all_ops = list(map(lambda x: x["op_name"],interpreter._get_ops_details()))
print(np.unique(all_ops))
```
I get this list: 
```
['ADD' 'BATCH_MATMUL' 'CAST' 'CONCATENATION' 'FULLY_CONNECTED' 'GATHER'
 'GELU' 'MEAN' 'MUL' 'PACK' 'REDUCE_PROD' 'RESHAPE' 'RSQRT' 'SHAPE'
 'SOFTMAX' 'SQUARED_DIFFERENCE' 'STRIDED_SLICE' 'SUB' 'TRANSPOSE']
```

I can see that some operators (e.g. GELU) are not in the list of supported operators, but my problem is that there should be an appropriate warning if the graph contains unsupported operators ([as described in the documentation](https://www.tensorflow.org/lite/performance/gpu#troubleshooting_gpu_support)). Furthermore, I did not even come to invoking the model, the creation of the Interpreter object with the GPU delegate option already crashes my application. If I could at least create an Interpreter and then run the model and it fails with these warnings, well then I know that supported ops could be a problem, but I do not even get to that point.

**Comment by gaikwadrahul8** [comment]
This issue originally reported by @DerEchteFeuerpfeil has been moved to this dedicated repository for [LiteRT](https://github.com/google-ai-edge/LiteRT/) to enhance issue tracking and prioritization. To ensure continuity, we have created this new issue on your behalf.

We appreciate your understanding and look forward to your continued involvement.

**Comment by pkgoogle** [comment]
Hi @DerEchteFeuerpfeil, have you tried this using [AI-Edge-Torch](https://github.com/google-ai-edge/ai-edge-torch) instead? Maybe this case is already handled w/ that workflow.
