### ISSUE TITLE
Python Wheel generation of TensorFlow Lite 2.17 for ARMv7l 32 bits not working

### ISSUE THREAD

**Issue by gaikwadrahul8** [google-ai-edge/LiteRT#37]
I have previously crosscompiled different versions of TensorFlow lite (2.14, 2.15.1, 2.16.2) for Python 3.10 using CMAKE and following the instructions from the [website ](https://ai.google.dev/edge/litert/build/cmake_pip). 

So far the only changes required were to just set my armhf flags as:

` echo "ARMCC_FLAGS=\"-march=armv7-a -mfpu=neon-vfpv3 -funsafe-math-optimizations \
`
adjust the python version in the MakeFile (tensorflow/lite/tools/pip_package/Makefile) and run the make command as:

` make -C tensorflow/lite/tools/pip_package docker-build \ TENSORFLOW_TARGET=armhf PYTHON_VERSION=3.10
`
Now, I have tried the same approach for the release 2.17.0 ( ad6d8cc ) and although the build is executed and the wheel is generated without errors, I keep getting the following errorat the moment of importing the interpreter:

```
python3 simpletest.py 
Traceback (most recent call last):
  File "/mnt/simpletest.py", line 2, in <module>
    import tflite_runtime.interpreter as tflite
  File "/usr/local/lib/python3.10/dist-packages/tflite_runtime/interpreter.py", line 33, in <module>
    from tflite_runtime import _pywrap_tensorflow_interpreter_wrapper as _interpreter_wrapper
ImportError: /usr/local/lib/python3.10/dist-packages/tflite_runtime/_pywrap_tensorflow_interpreter_wrapper.so: undefined symbol: TfLiteXNNPackDelegateOptionsDefault
```

**Comment by gaikwadrahul8** [comment]
This issue originally reported by @paguilar-pxc has been moved to this dedicated repository for [LiteRT](https://github.com/google-ai-edge/LiteRT/) to enhance issue tracking and prioritization. To ensure continuity, we have created this new issue on your behalf.

We appreciate your understanding and look forward to your continued involvement.

**Comment by harshithn31** [comment]
Hey, 
Are there any updates on the issue? 
Even I'm encountering the same issue and looking for solutions to resolve it.

**Comment by harshithn31** [comment]
Hey @gaikwadrahul8, @paguilar-pxc, 
I did manage to cross-compile TFLite for Arm Cortex-A9 (ARMv7 architecture with vfpv3).
using Python version 3.10 and TensorFlow version v2.15.0.

I have written a detailed blog. Feel free to go through it and write back.

[Cross-Compiling TensorFlow Lite for ZYNQ 7000 (ARMv7-A + VFPv3)](https://medium.com/@harshith.n001/cross-compiling-tensorflow-lite-for-zynq-7000-armv7-a-vfpv3-1a5e0358b83e)

**Comment by pkgoogle** [comment]
Hi @paguilar-pxc and @harshithn31, can you guys try cross-compiling with this: https://github.com/google-ai-edge/LiteRT/tree/main/build? Please change the target as appropriate to your use case -- if that doesn't work please let us know the reproduce steps you attempted.

**Comment by timber77** [comment]
I think I encounter the same issue. Although I am trying to build natively on a RISC-V machine with a slightly modified build script.
I think it's related to disabling XNNPACK.
@pkgoogle Unfortunately I cant built with docker, and need to build with cmake. Thus I am still using the main tensorflow repo as the source. Does LiteRT not have something like build_pip_package_with_cmake.sh?

**Comment by aravindmurali22** [comment]
Hi @paguilar-pxc,  Apologies for the delayed response.

Could you please check if this issue persists with the latest version of LiteRT? Additionally, did you have a chance to try the cross-compilation steps suggested by @pkgoogle above? If you are still encountering the `undefined symbol: TfLiteXNNPackDelegateOptionsDefault` error, please let us know.

**Comment by paguilar-pxc** [comment]
Hi @aravindmurali22, 

just like a month ago I tried again with the exact same results. I tried TFLite 2.19 and 2.20, both gave me the same results. 

Regarding compilation of LiteRT, I require a python wheel for my project and the instructions given for a python wheel are exactly the same as for TFLite so, that really didnt take me any further.

**Comment by aravindmurali22** [comment]
Hi @paguilar-pxc,

Thank you for taking the time to report this and for your patience. With the transition to LiteRT, we are closing legacy issues to keep our tracker aligned with the current codebase and release cycle. 

Please retry with [LiteRT v2](https://github.com/google-ai-edge/LiteRT/releases/tag/v2.1.5) and if it still fails, file a new issue with the updated details. This will help us track and investigate it using the most current LiteRT-specific context.

Thank you again for your support and understanding!
